Repository Manzoomeh/BasisCore.Client-v2, pull requests merged in 2024-09, with the labels that each got.

#57 add body to config
  example/component/source/dbsource/chunkBased/simple/example.html
  package.json
  server/chunk-server.js
  src/options/connection-options/ChunkBasedConnectionOptions.ts
Labels: enhancement

#61 Fix chunk system bug #60
  example/component/source/dbsource/chunkBased/simple/app.html
  src/index.ts
  src/options/connection-options/ChunkBasedConnectionOptions.ts
Labels: bug

#65 Adding event property to callback command for handle event Handler of dom #64
  example/component/source/callback/event/index.html
  example/component/source/callback/partial-load/index.html
  example/component/source/callback/timer/index.html
  example/index.html
  package.json
  src/component/ElementBaseComponent.ts
  src/component/renderable/base/FaceCollection.ts
  src/component/renderable/base/RenderableComponent.ts
  src/index.ts
  src/repository/Repository.ts
Labels: bug, enhancement
